import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    id("org.jetbrains.kotlin.jvm")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("org.jetbrains.compose")
}

// gradle.properties keeps snake_case keys, matching the mod build, so the
// values are read by name rather than through property delegation.
val launcherVersion = property("launcher_version") as String
val installerVersion = property("package_version") as String
val serializationVersion = property("serialization_version") as String
val coroutinesVersion = property("coroutines_version") as String
val junitVersion = property("junit_version") as String
val javaVersion = property("java_version") as String

group = property("maven_group") as String
version = launcherVersion

kotlin {
    jvmToolchain(javaVersion.toInt())
}

dependencies {
    implementation(compose.desktop.currentOs)
    implementation(compose.material3)
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:$serializationVersion")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:$coroutinesVersion")

    testImplementation(kotlin("test"))
    testImplementation(platform("org.junit:junit-bom:$junitVersion"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// The domain and application layers have no Compose and no filesystem
// dependency, so their tests are plain JUnit and need no windowing system.
tasks.test {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}

// The launcher reports its own version on the home screen and in every log
// file, so the build hands the value to the code rather than duplicating it.
val generateBuildInfo by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/buildinfo")
    val value = launcherVersion
    inputs.property("launcherVersion", value)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("dev/survivaloverhaul/launcher/BuildInfo.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by the Gradle task generateBuildInfo. Do not edit.
            |package dev.survivaloverhaul.launcher
            |
            |internal object BuildInfo {
            |    const val VERSION: String = "$value"
            |}
            |
            """.trimMargin()
        )
    }
}

kotlin.sourceSets.named("main") {
    kotlin.srcDir(generateBuildInfo)
}

compose.desktop {
    application {
        mainClass = "dev.survivaloverhaul.launcher.MainKt"

        nativeDistributions {
            targetFormats(TargetFormat.Msi, TargetFormat.Deb)
            packageName = "SurvivalOverhaul"
            packageVersion = installerVersion
            description = "Unofficial launcher for the Survival Overhaul Minecraft mod"
            vendor = "Survival Overhaul"
            copyright = "Not affiliated with Mojang Studios or Microsoft"

            // jlink strips the JDK down to what is listed here. java.net.http is
            // needed by every download the installer does; jdk.crypto.ec is
            // needed for TLS against Mojang's CDN; jdk.httpserver is the
            // loopback socket a Microsoft sign-in is redirected back to.
            modules(
                "java.net.http",
                "java.naming",
                "jdk.crypto.ec",
                "java.management",
                "jdk.httpserver",
            )

            windows {
                menu = true
                shortcut = true
                dirChooser = true
                // Fixed for the life of the product: changing it turns an
                // upgrade into a second, parallel installation.
                upgradeUuid = "351251D0-A624-420B-9A41-F8EDF484CF93"
            }

            linux {
                packageName = "survival-overhaul"
                menuGroup = "Game"
            }
        }
    }
}
